### ISSUE TITLE
After News-App activation, admin section gives error

### ISSUE THREAD

**Issue by quixony** [owncloud/news#773]
When the NewsApp is activated the adminpanel gives errors. When deactivating the app I can open panel as desired. 

### Steps to reproduce
1. Fresh Owncloud 8.0.02 installation
2. Install news app along the manual
3. Activate news app (updated to latest Version 5.2.0)
4. try to open admin section as administrator

### Expected behaviour
Normally admin section can be visited and options may be changed

### Actual behaviour
admin section will show an "Internal Server Error" error like 

### Server configuration
**Operating system**: Debian 
**Web server:** nginx
**Database:** mysql
**PHP version:** 5.0.2
**ownCloud version:** 8.0.0.2
**ownCloud fresh install:**

**List of activated apps:**
Activity, Bookmarks, Calendar, contacts, Deleted Files, File Locking, First Run Wizard, Mail Template Editor, Mozilla Sync, News, PDF Viewer, Pictures, Provisioning API, Share Files, Updater, Versions

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocl7ox54ml2v',
  'trusted_domains' =>
  array (
    0 => 'oc8.omv',
    1 => 'oc.omv',
  ),
  'datadirectory' => '/media/a664d858-b02b-42da-9a37-8fb93d97ea7b/owncloud8',
  'overwrite.cli.url' => 'https://oc8.omv',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud8',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'XxXxXxXxXxXxXx',
  'installed' => true,
  'maintenance' => false,
  'log_type' => 'owncloud',
  'logfile' => '/var/www/owncloud8/log/owncloud.log',
  'loglevel' => 0,
);

```

encryption: no

### Client configuration
Win7 x32 with Firefox 36 or Chrome

#### ownCloud log (data/owncloud.log)
```{"reqId":"998f30b834876c8e1e6a23cb640774ed","remoteAddr":"192.168.178.20","app":"lock","message":"INFO: Read lock requested for \/media\/a664d858-b02b-42da-9a37-8fb93d97ea7b\/owncloud8\/news\/config\/config.ini","level":0,"time":"2015-04-25T13:37:38+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"998f30b834876c8e1e6a23cb640774ed","remoteAddr":"192.168.178.20","app":"lock","message":"PASS: Acquired read lock for \/media\/a664d858-b02b-42da-9a37-8fb93d97ea7b\/owncloud8\/news\/config\/config.ini","level":0,"time":"2015-04-25T13:37:38+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"998f30b834876c8e1e6a23cb640774ed","remoteAddr":"192.168.178.20","app":"lock","message":"INFO: Incrementing lock type 1 count for \/media\/a664d858-b02b-42da-9a37-8fb93d97ea7b\/owncloud8\/news\/config\/config.ini","level":0,"time":"2015-04-25T13:37:38+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"998f30b834876c8e1e6a23cb640774ed","remoteAddr":"192.168.178.20","app":"lock","message":"INFO: Releasing locks on \/media\/a664d858-b02b-42da-9a37-8fb93d97ea7b\/owncloud8\/news\/config\/config.ini","level":0,"time":"2015-04-25T13:37:38+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"998f30b834876c8e1e6a23cb640774ed","remoteAddr":"192.168.178.20","app":"lock","message":"INFO: Released lock handle Resource id #592 on \/media\/a664d858-b02b-42da-9a37-8fb93d97ea7b\/owncloud8\/news\/config\/config.ini","level":0,"time":"2015-04-25T13:37:38+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"998f30b834876c8e1e6a23cb640774ed","remoteAddr":"192.168.178.20","app":"lock","message":"FREE: Released locks on \/media\/a664d858-b02b-42da-9a37-8fb93d97ea7b\/owncloud8\/news\/config\/config.ini","level":0,"time":"2015-04-25T13:37:38+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"998f30b834876c8e1e6a23cb640774ed","remoteAddr":"192.168.178.20","app":"index","message":"Exception: {\"Message\":\"Could not resolve ConfigPath! Class ConfigPath does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud8\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(93): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('ConfigPath')\\n#1 \\\/var\\\/www\\\/owncloud8\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(55): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('ConfigPath')\\n#2 \\\/var\\\/www\\\/owncloud8\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(73): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#3 \\\/var\\\/www\\\/owncloud8\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(93): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\News\\\\\\\\Contro...')\\n#4 \\\/var\\\/www\\\/owncloud8\\\/apps\\\/news\\\/admin\\\/admin.php(20): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\News\\\\\\\\Contro...')\\n#5 \\\/var\\\/www\\\/owncloud8\\\/lib\\\/private\\\/app.php(720): include('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud8\\\/settings\\\/admin.php(92): OC_App::getForms('admin')\\n#7 \\\/var\\\/www\\\/owncloud8\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/var\\\/www\\\/owncloud8\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_3818', Array)\\n#10 \\\/var\\\/www\\\/owncloud8\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#11 \\\/var\\\/www\\\/owncloud8\\\/index.php(36): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud8\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php\",\"Line\":79}","level":4,"time":"2015-04-25T13:37:38+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
```

**Comment by Raydiation** [comment]
Which news release do you use?

**Comment by quixony** [comment]
I am sorry, missed to write that down. Added it to the first post. 

I have installed it via git-clone, activated and updated via OwnCloud Interface to the offered Version. Right now it's the 5.2.0.

**Comment by Raydiation** [comment]
Ok, update, that problem was fixed ;)

**Comment by Raydiation** [comment]
Check 5.2.1 at https://github.com/owncloud/news/blob/master/CHANGELOG.md
