### ISSUE TITLE
news app does not load

### ISSUE THREAD

**Issue by Florz** [owncloud/news#802]
The app stopped showing any content. At first it seemed like the app was not updating some feeds anymore so I tried to update to the latest tagged version. Unfortunately this version required OC 8.1 so I downgraded back to the latest compatible version.
This left me with a blank page instead of any feeds. In my browser I could identify the following problems:

https://[...]/owncloud/index.php/apps/news/feeds/active -> 500 Internal Server Error
https://[...]/owncloud/index.php/apps/news/feeds -> 500 Internal Server Error

**ownCloud version**
owncloud-server 8.0.3-2

**News version**
4.3.2

**Browser and version**
Firefox 37.0.1

**PHP version**
PHP 5.6.7-1 (cli) (built: Mar 24 2015 12:30:15) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

**Distribution**
Debian testing
Codename: stretch
-> *deb http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/ /*

**data/owncloud.log**

```
{"reqId":"608215152162af88685a9d9de4e8a8fc","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"t
ime":"2015-05-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"608215152162af88685a9d9de4e8a8fc","remoteAddr":"::1","app":"lock","message":"INFO: Read lock requested for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2
015-05-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"608215152162af88685a9d9de4e8a8fc","remoteAddr":"::1","app":"lock","message":"PASS: Acquired read lock for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"20
15-05-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"608215152162af88685a9d9de4e8a8fc","remoteAddr":"::1","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":
0,"time":"2015-05-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"608215152162af88685a9d9de4e8a8fc","remoteAddr":"::1","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-0
5-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"608215152162af88685a9d9de4e8a8fc","remoteAddr":"::1","app":"lock","message":"INFO: Released lock handle Resource id #296 on \/var\/www\/owncloud\/data\/news\/config\/config.ini","l
evel":0,"time":"2015-05-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"608215152162af88685a9d9de4e8a8fc","remoteAddr":"::1","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05
-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"608215152162af88685a9d9de4e8a8fc","remoteAddr":"::1","app":"index","message":"Exception: {\"Message\":\"ordering is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www
\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(134): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('ordering', Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/app
framework\\\/db\\\/entity.php(67): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setOrdering', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(67):
 OCA\\\\News\\\\Db\\\\Feed->setOrdering('0')\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\
/db\\\/mapper.php(253): call_user_func('\\\\\\\\OCA\\\\\\\\News\\\\\\\\Db\\\\\\\\Fe...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(271): OCP
\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/var\\\/www\\\/news\\\/db\\\/feedmapper.php(77): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT `feeds`....', Array
)\\n#7 \\\/var\\\/www\\\/news\\\/service\\\/feedservice.php(73): OCA\\\\News\\\\Db\\\\FeedMapper->findAllFromUser('florz')\\n#8 \\\/var\\\/www\\\/news\\\/controller\\\/feedcontroller.php(64)
: OCA\\\\News\\\\Service\\\\FeedService->findAll('florz')\\n#9 [internal function]: OCA\\\\News\\\\Controller\\\\FeedController->index()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\
/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFr
amework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(9
7): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/rou
ting\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FeedController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal functi
on]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFrame
work\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/feed...')\\n#17 \\\/var\\\/www\\\/o
wncloud\\\/index.php(36): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php\",\"Line\":107}","level":4,"time":"201
5-05-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"3043af86acf01d5fb83b6767ef6a56c3","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"t
ime":"2015-05-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"3043af86acf01d5fb83b6767ef6a56c3","remoteAddr":"::1","app":"lock","message":"INFO: Read lock requested for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2
015-05-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"3043af86acf01d5fb83b6767ef6a56c3","remoteAddr":"::1","app":"lock","message":"PASS: Acquired read lock for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"20
15-05-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"3043af86acf01d5fb83b6767ef6a56c3","remoteAddr":"::1","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":
0,"time":"2015-05-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"3043af86acf01d5fb83b6767ef6a56c3","remoteAddr":"::1","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-0
5-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"3043af86acf01d5fb83b6767ef6a56c3","remoteAddr":"::1","app":"lock","message":"INFO: Released lock handle Resource id #296 on \/var\/www\/owncloud\/data\/news\/config\/config.ini","l
evel":0,"time":"2015-05-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"3043af86acf01d5fb83b6767ef6a56c3","remoteAddr":"::1","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05
-26T13:23:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"f255d0fdcbd44c245852f3490da8d5fc","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"t
ime":"2015-05-26T13:23:53+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"5b382424cfb8da7eb7af4e8eb47cc4e2","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"t
ime":"2015-05-26T13:23:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/"}
{"reqId":"5b382424cfb8da7eb7af4e8eb47cc4e2","remoteAddr":"::1","app":"lock","message":"INFO: Read lock requested for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2
015-05-26T13:23:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/"}
{"reqId":"5b382424cfb8da7eb7af4e8eb47cc4e2","remoteAddr":"::1","app":"lock","message":"PASS: Acquired read lock for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"20
15-05-26T13:23:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/"}
{"reqId":"5b382424cfb8da7eb7af4e8eb47cc4e2","remoteAddr":"::1","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":
0,"time":"2015-05-26T13:23:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/"}
{"reqId":"5b382424cfb8da7eb7af4e8eb47cc4e2","remoteAddr":"::1","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:23:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/"}
{"reqId":"5b382424cfb8da7eb7af4e8eb47cc4e2","remoteAddr":"::1","app":"lock","message":"INFO: Released lock handle Resource id #297 on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:23:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/"}
{"reqId":"5b382424cfb8da7eb7af4e8eb47cc4e2","remoteAddr":"::1","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:23:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/"}
{"reqId":"9e2be669d8f9793c24248568501a3bbc","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:23:57+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=b5153793e95b7f28951cfe79ab38ad02"}
{"reqId":"50d40b359792ddd96f5e881a5623d8bf","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:23:59+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/Desktop"}
{"reqId":"098a42f3eb63139ed7a3eeea5d38b478","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:23:59+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/Eigene%20Dateien"}
{"reqId":"e242df90b9e9749b4e2435dac48659d4","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:23:59+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/home\/StarMoney"}
{"reqId":"77595b1121383aa1610410107448a8a9","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:24:00+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/Documents"}
{"reqId":"fda74e54cb0f1f5be879f07a6c934368","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:24:00+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"79d2510ace67dbc20eb38148fa9b53df","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:24:00+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/home\/.thunderbird"}
{"reqId":"32418900a42a9e769deda956252343e5","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/avatar\/florz\/128?requesttoken=kbDTsudKLNa7f22QVt6sxBwN478mwo"}
{"reqId":"aefecc197ce1998753b355b51f244577","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/settings"}
{"reqId":"aefecc197ce1998753b355b51f244577","remoteAddr":"::1","app":"lock","message":"INFO: Read lock requested for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/settings"}
{"reqId":"aefecc197ce1998753b355b51f244577","remoteAddr":"::1","app":"lock","message":"PASS: Acquired read lock for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/settings"}
{"reqId":"aefecc197ce1998753b355b51f244577","remoteAddr":"::1","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/settings"}
{"reqId":"aefecc197ce1998753b355b51f244577","remoteAddr":"::1","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/settings"}
{"reqId":"aefecc197ce1998753b355b51f244577","remoteAddr":"::1","app":"lock","message":"INFO: Released lock handle Resource id #297 on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/settings"}
{"reqId":"aefecc197ce1998753b355b51f244577","remoteAddr":"::1","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/settings"}
{"reqId":"b635b1593cc4d41568c0bcc831beeda8","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds\/active"}
{"reqId":"b635b1593cc4d41568c0bcc831beeda8","remoteAddr":"::1","app":"lock","message":"INFO: Read lock requested for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds\/active"}
{"reqId":"b635b1593cc4d41568c0bcc831beeda8","remoteAddr":"::1","app":"lock","message":"PASS: Acquired read lock for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds\/active"}
{"reqId":"b635b1593cc4d41568c0bcc831beeda8","remoteAddr":"::1","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds\/active"}
{"reqId":"b635b1593cc4d41568c0bcc831beeda8","remoteAddr":"::1","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds\/active"}
{"reqId":"b635b1593cc4d41568c0bcc831beeda8","remoteAddr":"::1","app":"lock","message":"INFO: Released lock handle Resource id #296 on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds\/active"}
{"reqId":"b635b1593cc4d41568c0bcc831beeda8","remoteAddr":"::1","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds\/active"}
{"reqId":"b635b1593cc4d41568c0bcc831beeda8","remoteAddr":"::1","app":"index","message":"Exception: {\"Message\":\"ordering is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(134): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('ordering', Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(67): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setOrdering', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(67): OCA\\\\News\\\\Db\\\\Feed->setOrdering('0')\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(253): call_user_func('\\\\\\\\OCA\\\\\\\\News\\\\\\\\Db\\\\\\\\Fe...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(290): OCP\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/var\\\/www\\\/news\\\/db\\\/feedmapper.php(48): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT `feeds`....', Array)\\n#7 \\\/var\\\/www\\\/news\\\/service\\\/service.php(54): OCA\\\\News\\\\Db\\\\FeedMapper->find(37, 'florz')\\n#8 \\\/var\\\/www\\\/news\\\/controller\\\/feedcontroller.php(100): OCA\\\\News\\\\Service\\\\Service->find(37, 'florz')\\n#9 [internal function]: OCA\\\\News\\\\Controller\\\\FeedController->active()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'active')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'active')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FeedController', 'active', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/feed...')\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php\",\"Line\":107}","level":4,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds\/active"}
{"reqId":"ebacf9b87cd880e796f36b1814ec2733","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"ebacf9b87cd880e796f36b1814ec2733","remoteAddr":"::1","app":"lock","message":"INFO: Read lock requested for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"ebacf9b87cd880e796f36b1814ec2733","remoteAddr":"::1","app":"lock","message":"PASS: Acquired read lock for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"ebacf9b87cd880e796f36b1814ec2733","remoteAddr":"::1","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"ebacf9b87cd880e796f36b1814ec2733","remoteAddr":"::1","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"ebacf9b87cd880e796f36b1814ec2733","remoteAddr":"::1","app":"lock","message":"INFO: Released lock handle Resource id #296 on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"ebacf9b87cd880e796f36b1814ec2733","remoteAddr":"::1","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"ebacf9b87cd880e796f36b1814ec2733","remoteAddr":"::1","app":"index","message":"Exception: {\"Message\":\"ordering is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(134): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('ordering', Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(67): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setOrdering', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(67): OCA\\\\News\\\\Db\\\\Feed->setOrdering('0')\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(253): call_user_func('\\\\\\\\OCA\\\\\\\\News\\\\\\\\Db\\\\\\\\Fe...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(271): OCP\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/var\\\/www\\\/news\\\/db\\\/feedmapper.php(77): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT `feeds`....', Array)\\n#7 \\\/var\\\/www\\\/news\\\/service\\\/feedservice.php(73): OCA\\\\News\\\\Db\\\\FeedMapper->findAllFromUser('florz')\\n#8 \\\/var\\\/www\\\/news\\\/controller\\\/feedcontroller.php(64): OCA\\\\News\\\\Service\\\\FeedService->findAll('florz')\\n#9 [internal function]: OCA\\\\News\\\\Controller\\\\FeedController->index()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FeedController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/feed...')\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php\",\"Line\":107}","level":4,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"c1061a3dd7cdf3f139366320935a01f0","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"c1061a3dd7cdf3f139366320935a01f0","remoteAddr":"::1","app":"lock","message":"INFO: Read lock requested for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"c1061a3dd7cdf3f139366320935a01f0","remoteAddr":"::1","app":"lock","message":"PASS: Acquired read lock for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"c1061a3dd7cdf3f139366320935a01f0","remoteAddr":"::1","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"c1061a3dd7cdf3f139366320935a01f0","remoteAddr":"::1","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"c1061a3dd7cdf3f139366320935a01f0","remoteAddr":"::1","app":"lock","message":"INFO: Released lock handle Resource id #296 on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"c1061a3dd7cdf3f139366320935a01f0","remoteAddr":"::1","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-26T13:24:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"edcaa27704aeb7a42bec95b8353ab23f","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:24:08+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"3933c46f3d4d70c5c7689f90cce6332c","remoteAddr":"::1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-26T13:24:09+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
```

**Comment by Raydiation** [comment]
Youve dropped to a way too low version, try 5.2.x

**Comment by Raydiation** [comment]
And delete the **ordering** column from your **oc_news_items** table

**Comment by Raydiation** [comment]
The ordering column was added somewhere around 5.x so if you want to use a newer version than the one you've reported you can keep the column ofc

**Comment by Raydiation** [comment]
You should keep track of the change log BTW https://github.com/owncloud/news/blob/master/CHANGELOG.md

**Comment by Florz** [comment]
Thanks, that was my fault. I switched to 5.2.8 and restored the items table from this mornings backup. Now it is working again.
