### ISSUE TITLE
News not marking as read, after upgrading to 8.1&5.3.8

### ISSUE THREAD

**Issue by tnako** [owncloud/news#824]
**ownCloud Version:** 8.1
**News Version:** 5.3.8
**Browser and version:** chromium-44.0.2403.61
**PHP:** 5.6.10-pl0-gentoo
**Distribution:** gentoo owncloud + news from github

What i try to do
- to use 5.3.5 and master 
- disabling and enabling application
- mark all news as read
- change favourity

It like read-only mode in browser (
But new news added by cron

data/owncloud.log with debug
```
{"reqId":"JaGxod80qMbsYZEtTgQq","remoteAddr":"127.0.0.1","app":"base","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"session_start(): Cannot send session cache limiter - headers already sent\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(2, 'session_start()...', '\\\/var\\\/www\\\/localh...', 38, Array)\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php(38): session_start()\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(454): OC\\\\Session\\\\Internal->__construct('5200e15e89d9d')\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(594): OC::initSession()\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(1115): OC::init()\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/index.php(38): require_once('\\\/var\\\/www\\\/localh...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php\",\"Line\":104}","level":4,"time":"2015-07-09T15:12:08+00:00","method":"POST","url":"\/index.php\/apps\/news\/items\/73924\/read"}
{"reqId":"JaGxod80qMbsYZEtTgQq","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"Cannot modify header information - headers already sent\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(2, 'Cannot modify h...', '\\\/var\\\/www\\\/localh...', 103, Array)\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/response.php(103): header('HTTP\\\/1.1 500 In...')\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(460): OC_Response::setStatus(500)\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(594): OC::initSession()\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(1115): OC::init()\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/index.php(38): require_once('\\\/var\\\/www\\\/localh...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php\",\"Line\":104}","level":4,"time":"2015-07-09T15:12:08+00:00","method":"POST","url":"\/index.php\/apps\/news\/items\/73924\/read"}
{"reqId":"JaGxod80qMbsYZEtTgQq","remoteAddr":"127.0.0.1","app":"PHP","message":"Cannot modify header information - headers already sent at Unknown#0","level":3,"time":"2015-07-09T15:12:08+00:00","method":"POST","url":"\/index.php\/apps\/news\/items\/73924\/read"}

```

**Comment by Raydiation** [comment]
Please reformat your report to follow https://github.com/owncloud/news#bugs

**Comment by Raydiation** [comment]
And the faq entry https://github.com/owncloud/news#feeds-are-not-updated

**Comment by tnako** [comment]
Reformated, cron is working, news added every 15 minute

**Comment by Raydiation** [comment]
Check the first log entry, your server can't start the session, probably your php is misconfigured

**Comment by Raydiation** [comment]
Could also be a bad app

**Comment by tnako** [comment]
Set **display_errors = off** helps, need more investigation
