### ISSUE TITLE
Updating to 6.0.3 breaks app

### ISSUE THREAD

**Issue by AsavarTzeth** [owncloud/news#856]
I just updated the app using the application section of ownCloud (appstore) and now it is broken.

I did try to verify the installation via `occ news:verify-install`

### Steps to reproduce
1. Navigate to the integrated application management
2. Update from previous version to current one (6.0.3)
3. Launch the app

### Expected behaviour
The app launches when clicked

### Actual behaviour
Loading fails and ownCloud tells me to check the log for errors

### Server configuration
**Operating system**:
Ubuntu 15.04

**Web server:**
nginx 1.6.2-5ubuntu3.1

**Database:**
postgresql 9.4.4-0ubuntu0.15.04

**PHP version:**
php-fpm 5.6.4+dfsg-4ubuntu6.2

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.1 (stable)

**Updated from an older ownCloud or fresh install:**
updated

**List of activated apps:**

```
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.3
 - contacts: 0.4.0.0
 - documents: 0.10.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 13.0.0
 - music: 0.3.7
 - news: 6.0.3
 - provisioning_api: 0.2
 - templateeditor: 0.1
Disabled:
 - encryption
 - external
 - gallery
 - music.old
 - ownnote
 - storagecharts2
 - tasks
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => 'cloud.hembas.se',
  ),
  'datadirectory' => '/volume1/owncloud',
  'overwrite.cli.url' => 'https://cloud.hembas.se',
  'dbtype' => 'pgsql',
  'version' => '8.1.1.3',
  'dbpassword' => '',
  'dbhost' => '/var/run/postgresql',
  'dbtableprefix' => 'oc_',
  'installed' => 'true',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_domain' => 'cloud.hembas.se',
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'info',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'logfile' => '/var/log/nginx/owncloud.log',
  'logtimezone' => 'Europe/Stockholm',
  'asset-pipeline.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** 
no

### Client configuration
**Browser:**
Chromium 45.0.2454.85 (64-bit)

**Operating system:**
Arch Linux

#### Web server error log
Nothing related to news app

#### ownCloud log (data/owncloud.log)
```
{"reqId":"dQ9ka4\/qYo2RXtNdjXAi","remoteAddr":"x.x.x.x","app":"index","message":"Exception: {\"Exception\":\"BadFunctionCallException\",\"Message\":\"pinned is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(145): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('pinned', Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setPinned', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCA\\\\News\\\\Db\\\\Feed->setPinned(false)\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(305): call_user_func('\\\\\\\\OCA\\\\\\\\News\\\\\\\\Db\\\\\\\\Fe...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(324): OCP\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/db\\\/feedmapper.php(77): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT `feeds`....', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/service\\\/feedservice.php(72): OCA\\\\News\\\\Db\\\\FeedMapper->findAllFromUser('asavartzeth')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/controller\\\/feedcontroller.php(64): OCA\\\\News\\\\Service\\\\FeedService->findAll('asavartzeth')\\n#9 [internal function]: OCA\\\\News\\\\Controller\\\\FeedController->index()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FeedController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/feed...')\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php\",\"Line\":114}","level":4,"time":"2015-09-11T13:12:04+02:00"}
{"reqId":"77HSIbU\/FgI8cJnhC32u","remoteAddr":"x.x.x.x","app":"index","message":"Exception: {\"Exception\":\"BadFunctionCallException\",\"Message\":\"pinned is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(145): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('pinned', Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setPinned', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCA\\\\News\\\\Db\\\\Feed->setPinned(false)\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(305): call_user_func('\\\\\\\\OCA\\\\\\\\News\\\\\\\\Db\\\\\\\\Fe...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(324): OCP\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/db\\\/feedmapper.php(77): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT `feeds`....', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/service\\\/feedservice.php(72): OCA\\\\News\\\\Db\\\\FeedMapper->findAllFromUser('asavartzeth')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/controller\\\/itemcontroller.php(103): OCA\\\\News\\\\Service\\\\FeedService->findAll('asavartzeth')\\n#9 [internal function]: OCA\\\\News\\\\Controller\\\\ItemController->index(3, NULL, 40, 0, false, false, '')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\ItemController), 'index')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\ItemController), 'index')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ItemController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/item...')\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php\",\"Line\":114}","level":4,"time":"2015-09-11T13:12:05+02:00"}
```

#### Browser log
Not sure how to do this

**Comment by AsavarTzeth** [comment]
Ok update. Thanks to the support of the developer of the tasks app I figured out that caching (possibly from APCu) is breaking the upgrade. A clean reinstall with the php and web server daemon restarted fixed things.
