### ISSUE TITLE
502 errors citing news/api after Tasks app upgrade

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/news#901]
After a failed upgrade of the tasks app (reported at https://github.com/owncloud/tasks/issues/286 ) my ownCloud site just gives 502 errors, with the following news errors in the log. Even disabling news doesn't seem to get rid of the 502's.

Nginx logs show this repeatedly:
````
[error] 15381#0: *20266 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: mydomain.com, request: "GET /index.php/apps/news/api/v1-2/cleanup/before-update HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "mydomain.com"
````

The last errors in the ownCloud log are:

````

{"reqId":"n27YRvgQfC7tH7xEphcy","remoteAddr":"58.179.254.124","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/remote.php(137): require_once('\\\/srv\\\/http\\\/webap...')\\n#6 {main}\",\"File\":\"\\\/srv\\\/http\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/maintenanceplugin.php\",\"Line\":84}","level":4,"time":"Sun , 20 Dec 2015 - 07 02 pm"}
{"reqId":"T27d\/olhAZEiyB1qm4cl","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 53 pm"}
{"reqId":"A1sqOxrWFs5jOFGG9aa6","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 54 pm"}
{"reqId":"3yZgPqfTiOcdA8irQefy","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 54 pm"}
{"reqId":"R7k5CFlnfseHW\/8wC3JE","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 54 pm"}
{"reqId":"F3sjdGtb2wHiK42cfzW7","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 55 pm"}
{"reqId":"5\/vP+VltTOb8c0mrOrTg","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 55 pm"}
{"reqId":"+aXmEkp9PhDOjFqxbyZM","remoteAddr":"127.0.0.1","app":"core","message":"can't remove app tasks. It is not installed.","level":3,"time":"Tue , 22 Dec 2015 - 01 10 am"}
{"reqId":"UDnv8f3j5\/sCpbjxx\/HO","remoteAddr":"127.0.0.1","app":"core","message":"can't remove app tasks. It is not installed.","level":3,"time":"Tue , 22 Dec 2015 - 01 14 am"}
{"reqId":"kFbDMFAo6sn1d7mtR+os","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Tue , 22 Dec 2015 - 01 24 am"}

````

Disabling Tasks and News and using occ maintenance:repair doesn't seem to make any difference.

I also tried rerplacing the /apps/news folder with a newly downloaded version.

Despite these errors, the News app was working just fine before my attempted upgrade of Tasks, and I'm quite sure I only opted to upgrade Tasks and not News. Neither checksum.json or news/api appear to exist.

**Comment by BernhardPosselt** [comment]
Php cache?

**Comment by Bugsbane** [comment]
> Php cache?

What do you mean? Are you asking if I have any PHP caching turned on?

**Comment by BernhardPosselt** [comment]
Yep, can you clear it?

**Comment by Bugsbane** [comment]
Good question! I'll Google it, give it and try and let you know...

**Comment by Bugsbane** [comment]
Not sure what I'm doing, but the site uses apcu and so I created a php file with this inside:

````

<?php
  apc_clear_cache();
  apc_clear_cache('user');
  apc_clear_cache('opcode');
  echo json_encode(array('success' => true));
?>
````

...and accessed it via the web browser. While it echo'd true, it doesn't seem to make any difference. I still get just a 500 server error. systemctl status nginx -l gives:

> 2015/12/27 03:29:31 [error] 15381#0: *61564 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'OC\Setup' not found in /path/to/my/owncloud/lib/private/util.php on line 617" while reading response header from upstream, client: 127.0.0.1, server: mydomain.com, request: "GET /index.php/apps/news/api/v1-2/cleanup/before-update HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "mydomain.com"

**Comment by BernhardPosselt** [comment]
How about restarting your web server?

**Comment by BernhardPosselt** [comment]
Closing because of inactivity

**Comment by Bugsbane** [comment]
Sorry. I should have updated. Yes, clearing the PHP cache and restarting the server fixed the issue. Carry on. :)
