### ISSUE TITLE
News update eating up all memory

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/news#902]
Trying to upgrade from 5.3.9 to current:
time php -c /home/oc/php.ini ./occ upgrade --skip-migration-test --no-app-disable -vvv
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2016-01-03T02:10:10+00:00 Set log level to debug - current level: 'Debug'
2016-01-03T02:10:10+00:00 Repair step: Repair MySQL database engine
2016-01-03T02:10:10+00:00 Repair step: Repair MySQL collation
2016-01-03T02:10:10+00:00 Repair step: Repair SQLite autoincrement
2016-01-03T02:10:10+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2016-01-03T02:10:10+00:00 Repair info: removing duplicate entries from lucene_status
2016-01-03T02:10:10+00:00 Repair step: Repair config
2016-01-03T02:10:10+00:00 Updating database schema
2016-01-03T02:10:10+00:00 Updated database
2016-01-03T02:10:10+00:00 Updating <news> ...
PHP Fatal error:  Allowed memory size of 26239565824 bytes exhausted (tried to allocate 72 bytes) in /var/www/oc/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 128

real	3m48.886s
user	1m55.059s
sys	1m47.313s
[oc@srv02]$ 

The PHP script was given 25GB of memory, still it's not enough?

Our News apps is down due to this :(

@BernhardPosselt

**Comment by fossxplorer** [comment]
I've tried to git checkout tags/5.3.9 to get the oC working. News won't work anymore and here is the log error message:

{"reqId":"hJbyM2IqTdCseurKu9tD","remoteAddr":"192.168.0.1","app":"index","message":"Exception: {\"Exception\":\"BadFunctionCallException\",\"Message\":\"updateErrorCount is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\oc\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(145): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('updateErrorCoun...', Array)\\n#1 \\\/var\\\/www\\\oc\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setUpdateErrorC...', Array)\\n#2 \\\/var\\\/www\\\oc\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCA\\\\News\\\\Db\\\\Feed->setUpdateErrorCount('0')\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/var\\\/www\\\oc\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(305): call_user_func('\\\\\\\\OCA\\\\\\\\News\\\\\\\\Db\\\\\\\\Fe...', Array)\\n#5 \\\/var\\\/www\\\oc\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(346): OCP\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/var\\\/www\\\oc\\/apps\\\/news\\\/db\\\/feedmapper.php(48): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT `feeds`....', Array)\\n#7 \\\/var\\\/www\\\oc\\/apps\\\/news\\\/service\\\/service.php(54): OCA\\\\News\\\\Db\\\\FeedMapper->find(4258, 'ocuser11')\\n#8 \\\/var\\\/www\\\oc\\/apps\\\/news\\\/controller\\\/feedcontroller.php(100): OCA\\\\News\\\\Service\\\\Service->find(4258, 'ocuser11')\\n#9 [internal function]: OCA\\\\News\\\\Controller\\\\FeedController->active()\\n#10 \\\/var\\\/www\\\oc\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\oc\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'active')\\n#12 \\\/var\\\/www\\\oc\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'active')\\n#13 \\\/var\\\/www\\\oc\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FeedController', 'active', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\oc\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\oc\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/feed...')\\n#17 \\\/var\\\/www\\\oc\\\/index.php(39): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\

**Comment by BernhardPosselt** [comment]
The bad function call exception usually happens when the database is newer than the model as in additional columns. Delete those and the downgrade will work again. There should be 2 new columns in the items table, both starting with update_error

**Comment by BernhardPosselt** [comment]
As for the memory issue: I've changed the code to generate search indices on upgrade like this https://github.com/owncloud/news/blob/master/service/itemservice.php

I don't know why it takes up so much RAM though because I'm only fetching all item id's in the form of an integer list. The object should be deallocated after each run in the foreach loop but your issue makes it look like instances are not thrown away. It would be cool if you could dive into this using a debugger and check where most RAM is actually allocated

**Comment by BernhardPosselt** [comment]
Another thing maybe php 7's reduced memory footprint solves the issue :)

**Comment by fossxplorer** [comment]
Ok.
Table looks like:
show create table oc_news_items\G
*************************** 1. row ***************************
       Table: oc_news_items
Create Table: CREATE TABLE `oc_news_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `guid_hash` varchar(32) COLLATE utf8_bin NOT NULL,
  `guid` longtext COLLATE utf8_bin NOT NULL,
  `url` longtext COLLATE utf8_bin,
  `title` longtext COLLATE utf8_bin,
  `author` longtext COLLATE utf8_bin,
  `pub_date` bigint(20) unsigned DEFAULT NULL,
  `body` longtext COLLATE utf8_bin,
  `enclosure_mime` longtext COLLATE utf8_bin,
  `enclosure_link` longtext COLLATE utf8_bin,
  `feed_id` bigint(20) NOT NULL,
  `status` bigint(20) NOT NULL DEFAULT '0',
  `last_modified` bigint(20) unsigned DEFAULT '0',
  `search_index` longtext COLLATE utf8_bin,
  `fingerprint` varchar(32) COLLATE utf8_bin DEFAULT NULL,
  `rtl` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `news_items_feed_id_index` (`feed_id`),
  KEY `news_items_item_guid` (`guid_hash`,`feed_id`),
  KEY `news_items_fingerprint_index` (`fingerprint`)
) ENGINE=TokuDB AUTO_INCREMENT=45545683 DEFAULT CHARSET=utf8 COLLATE=utf8_bin `compression`='tokudb_zlib'

Maybe using engine TokuDB is the issue? Has not been so far at least!

I can upgrade to PHP, but would be nice to just get News app  & running.
Using PHP 5.6 atm.

Btw, News is on 6.0.0 now, as when i checked out that tag, the upgrade went through.

**Comment by fossxplorer** [comment]
Ah, i found some update_*  + last_update_error columns in feeds table:
 `update_error_count` bigint(20) NOT NULL DEFAULT '0',
  `last_update_error` longtext COLLATE utf8_bin,
  `update_mode` int(11) NOT NULL DEFAULT '0',


Should they be deleted?

**Comment by BernhardPosselt** [comment]
Ah OK the auto migrate is only in master AFAIK so my assumption what could be the issue is wrong. As for the columns: simply check the appinfo/database.xml

**Comment by fossxplorer** [comment]
Ok. Yes, i see there is a mismatch between  appinfo/database.xml and the actual columns in the DB. 
Just to make sure: am i supposed to remove those columns not in appinfo/database.xml?
Thanks!

**Comment by fossxplorer** [comment]
Same goes for the items as i see the following columns not in database.xml:
search_index` longtext COLLATE utf8_bin,
  `fingerprint` varchar(32) COLLATE utf8_bin DEFAULT NULL,
  `rtl` tinyint(1) NOT NULL DEFAULT '0',

**Comment by BernhardPosselt** [comment]
Database. XML is the source of truth, so any column not in that file needs to be removed

**Comment by fossxplorer** [comment]
Yeah, finally after couple of hours with running alter table i was able to delete the columns.
Now we have a working News app again with version 6.0.0.
I'll debug upgrade to current master on a test server later on.
Thanks a lot @BernhardPosselt

**Comment by fossxplorer** [comment]
Hmm, now it's not possible to add or remove any RSS feed URL:
"app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_news_items`(`status`,`url`,`guid`,`guid_hash`,`pub_date`,`last_modified`,`title`,`author`,`body`,`search_index`,`feed_id`) VALUES(?,?,?,?,?,?,?,?,?,?,?)' with params [2, \\\"http:\\\\\\\/\\\\\\\/techcrunch.com\\\\\\\/2016\\\\\\\/01\\\\\\\/02\\\\\\\/april-underwood\\\\\\\/?ncid=rss\\\", \\\"923e1a6c9df25aa6eadcbd9f40407848\\\", \\\"923e1a6c9df25aa6eadcbd9f40407848\\\", 1451799816, 1451913960, \\\"Slack Promotes Former Twitter Boss April Underwood To VP Of Product\\\", \\\"Josh Constine\\\", \\\"<img src=\\\\\\\"https:\\\\\\\/\\\\\\\/tctechcrunch2011.files.wordpress.com\\\\\\\/2016\\\\\\\/01\\\\\\\/slack-april-underwood.png?w=640\\\\\\\" alt=\\\\\\\"Slack April Underwood\\\\\\\" \\\\\\\/> Slack\\\\u2019s rocket ship has a new co-pilot. April Underwood, Slack\\\\u2019s former head of platform who just launched its App Directory and Slack Fund, has leveled up to become the startup\\\\u2019s VP of Product. Underwood joined Slack in June after nearly five years at Twitter where she was a Director of Product. Putting the head of platform in charge of the entire product shows\\\\u2026 <a target=\\\\\\\"_blank\\\\\\\" rel=\\\\\\\"noreferrer\\\\\\\" href=\\\\\\\"http:\\\\\\\/\\\\\\\/techcrunch.com\\\\\\\/2016\\\\\\\/01\\\\\\\/02\\\\\\\/april-underwood\\\\\\\/?ncid=rss\\\\\\\">Read More<\\\\\\\/a>\\\", \\\" slack\\\\u2019s rocket ship has a new co-pilot. april underwood, slack\\\\u2019s former head of platform who just launched its app directory and slack fund, has leveled up to become the startup\\\\u2019s vp of product. underwood joined slack in june after nearly five years at twitter where she was a director of product. putting the head of platform in charge of the entire product shows\\\\u2026 read morejosh constineslack promotes former twitter boss april underwood to vp of producthttp:\\\\\\\/\\\\\\\/techcrunch.com\\\\\\\/2016\\\\\\\/01\\\\\\\/02\\\\\\\/april-underwood\\\\\\\/?ncid=rss\\\", 18451]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'search_index' in 'field list'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/\\\/oc\\\/public_html\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(250): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/var\\\/www\\\/\\\/oc\\\/public_html\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(124): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('INSERT INTO `*P...', Array)\\n#4 \\\/var\\\/www\\\/\\\/oc\\\/apps3\\\/news\\\/service\\\/feedservice.php(143): OCP\\\\AppFramework\\\\Db\\\\Mapper->insert(Object(OCA\\\\News\\\\Db\\\\Item))\\n#5 \\\/var\\\/www\\\/\\\/oc\\\/apps3\\\/news\\\/controller\\\/feedcontroller.php(136): OCA\\\\News\\\\Service\\\\FeedService->create('http:\\\/\\\/techcrun...', 2829, 'ocuser11', NULL)\\n#6 [internal function]: OCA\\\\News\\\\Controller\\\\FeedController->create('http:\\\/\\\/techcrun...', 2829, NULL)\\n#7 \\\/var\\\/www\\\/\\\/oc\\\/public_html\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/\\\/oc\\\/public_html\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'create')\\n#9 \\\/var\\\/www\\\/\\\/oc\\\/public_html\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'create')\\n#10 \\\/var\\\/www\\\/\\\/oc\\\/public_html\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FeedController', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/\\\/oc\\\/public_html\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/\\\/oc\\\/public_html\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/feed...')\\n#14 \\\/var\\\/www\\\/\\\/oc\\\/public_html\\\/index.php(39): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71}","level":3,"time":"2016-01-04T13:26:00+00:00","method":"POST","url":"\/index.php\/apps\/news\/feeds"}

@BernhardPosselt  Does version 6.0.0 introduce searching?
I need to go back to the version before this was introduced.

**Comment by BernhardPosselt** [comment]
Check the releases page ;) https://github.com/owncloud/news/releases

**Comment by fossxplorer** [comment]
Seems to be introduced in 6.0.3. But i realize now that i've deleted the column search_index from items table, mixing it to be search related to version 6.0.3.
What info did that column contain? Now i'll have to add that to fix it.

**Comment by BernhardPosselt** [comment]
Use this command: https://github.com/owncloud/news/tree/6.0.3#updating-from-versions-prior-to-530

**Comment by BernhardPosselt** [comment]
Ok, I've changed it to run in batches of 1000 and removed unneeded parameters from the sql query https://github.com/owncloud/news/blob/master/db/itemmapper.php#L353

Can you retry updating to master?

**Comment by BernhardPosselt** [comment]
PS: updating to master should fix all your issues

**Comment by fossxplorer** [comment]
Sure, i will try again and let you know. Thx a lot!

**Comment by BernhardPosselt** [comment]
Closing this because of inactivity. Should be fixed in 7.0.0 however, reopen if this is still an issue
