### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by enekux** [owncloud/news#907]
Hi,

when trying to configure the scripts to run with SystemD and run:

owncloud-news-updater -c /etc/owncloud/news/updater.ini

I get the next error:

# owncloud-news-updater -c /etc/owncloud/news/updater.ini
2016-01-14 15:05:09,097 - ownCloud News Updater - ERROR - https://hod.earde.si/owncloud/index.php/apps/news/api/v1-2: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused')) Trying again in 30 seconds
2016-01-14 15:05:39,213 - ownCloud News Updater - ERROR - https://hod.earde.si/owncloud/index.php/apps/news/api/v1-2: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused')) Trying again in 30 seconds
2016-01-14 15:06:09,291 - ownCloud News Updater - ERROR - https://hod.earde.si/owncloud/index.php/apps/news/api/v1-2: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused')) Trying again in 30 seconds
^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 203, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 133, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 87, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 624, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 203, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 133, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 87, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/owncloud_news_updater-7.0.0-py3.4.egg/owncloud_news_updater/updater.py", line 52, in run
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/owncloud-news-updater", line 9, in <module>
    load_entry_point('owncloud-news-updater==7.0.0', 'console_scripts', 'owncloud-news-updater')()
  File "/usr/local/lib/python3.4/dist-packages/owncloud_news_updater-7.0.0-py3.4.egg/owncloud_news_updater/application.py", line 86, in main
  File "/usr/local/lib/python3.4/dist-packages/owncloud_news_updater-7.0.0-py3.4.egg/owncloud_news_updater/updater.py", line 87, in run
KeyboardInterrupt

Any ideas, please?

Thank you,

**Comment by BernhardPosselt** [comment]
Did you specify an admin user in the ini?

**Comment by enekux** [comment]
Yes

**Comment by enekux** [comment]
# all values are optional and can be left out to require the argument being
# passed in from the command line

[updater]
user = enekux
password = ****
threads = 10
interval = 900
testrun = false
url = https://hodei.eande.si/owncloud

**Comment by BernhardPosselt** [comment]
Anyways your issue is that the request to your URL is refused. This can be due to not having sufficient access rights (user is not in admin group) or simply by being blocked.

**Comment by BernhardPosselt** [comment]
Also I can't find https://hod.earde.si/owncloud the website does not exist.

Another hint could be that port 443 is not open

**Comment by enekux** [comment]
Hi,

thank you for your support.
The link was fictitious ;)

I am running my Owncloud Server at home behind the router (NAT) so the server has a private ip 192.168.1.4. In order to fix the problem I have had to include the next line to the "/etc/hosts" file:

192.168.1.4	hod.earde.si

After that the next command

"owncloud-news-updater -c /etc/owncloud/news/updater.ini" did not complain and I started to get feeds again!!

Thank you and regards,
