### ISSUE TITLE
owncloud-news-updater doesn't work with python 3.5

### ISSUE THREAD

**Issue by ptah-alexs** [owncloud/news#920]
Debian sid, python3 --version "Python 3.5.1+":

```
/usr/bin# ./owncloud-news-updater
Traceback (most recent call last):
  File "./owncloud-news-updater", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 661, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 962, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'owncloud-news-updater==5.2.8' distribution was not found and is required by the application
```
If I lunch script with python 3.4, it work normally.

**Comment by BernhardPosselt** [comment]
You probably installed it only for 3.4 and not for 3.5 check the site-packages folder

**Comment by ptah-alexs** [comment]
Ooops, I didn't thought update need. After update it work, thanks.
