### ISSUE TITLE
make fails with 8.2.0.tar.gz

### ISSUE THREAD

**Issue by MrMontesa** [owncloud/news#965]
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [*] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
make fails on my system with error messages

## Steps to Reproduce
Explain what you did to encounter the issue
1. download, unzip https://github.com/owncloud/news/archive/8.2.0.tar.gz & cd
2. sudo -u www-data make fails miserably with unknown composer binary
3. make as root fails with error messages attached/below

## System Information
* News app version: 8.2.0
* ownCloud version: 9.0.0
* PHP version:PHP 5.6.17-0+deb8u1
* Database and version: mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu
* Browser and version: Chrome latest
* Distribution and version: Debian GNU/Linux 8 x86_64

## Contents of /var/www/owncloud/apps/news/npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'bugs', 'ownCloud-news' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 silly fetchPackageMetaData ownCloud-news
5 silly fetchNamedPackageData ownCloud-news
6 silly mapToRegistry name ownCloud-news
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'ownCloud-news',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   name: 'ownCloud-news',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/ownCloud-news
11 verbose request uri https://registry.npmjs.org/ownCloud-news
12 verbose request no auth needed
13 info attempt registry request try #1 at 14:05:20
14 verbose request id 8e1b245856de1636
15 http request GET https://registry.npmjs.org/ownCloud-news
16 http 404 https://registry.npmjs.org/ownCloud-news
17 verbose headers { 'content-type': 'application/json',
17 verbose headers   'cache-control': 'max-age=0',
17 verbose headers   'content-length': '2',
17 verbose headers   'accept-ranges': 'bytes',
17 verbose headers   date: 'Fri, 08 Apr 2016 12:05:21 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   age: '0',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-fra1237-FRA',
17 verbose headers   'x-cache': 'MISS',
17 verbose headers   'x-cache-hits': '0',
17 verbose headers   'x-timer': 'S1460117120.555308,VS0,VE702',
17 verbose headers   vary: 'Accept-Encoding' }
18 silly get cb [ 404,
18 silly get   { 'content-type': 'application/json',
18 silly get     'cache-control': 'max-age=0',
18 silly get     'content-length': '2',
18 silly get     'accept-ranges': 'bytes',
18 silly get     date: 'Fri, 08 Apr 2016 12:05:21 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     age: '0',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-fra1237-FRA',
18 silly get     'x-cache': 'MISS',
18 silly get     'x-cache-hits': '0',
18 silly get     'x-timer': 'S1460117120.555308,VS0,VE702',
18 silly get     vary: 'Accept-Encoding' } ]
19 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/ownCloud-news
19 silly fetchPackageMetaData     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
19 silly fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
19 silly fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:199:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:100:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:185:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1036:10)
19 silly fetchPackageMetaData     at emitOne (events.js:95:20)
19 silly fetchPackageMetaData     at Request.emit (events.js:182:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:963:12)
19 silly fetchPackageMetaData  error for ownCloud-news { [Error: Registry returned 404 for GET on https://registry.npmjs.org/ownCloud-news] pkgid: 'ownCloud-news', statusCode: 404, code: 'E404' }
20 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/ownCloud-news
20 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
20 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
20 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
20 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:199:22)
20 verbose stack     at emitTwo (events.js:100:13)
20 verbose stack     at Request.emit (events.js:185:7)
20 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1036:10)
20 verbose stack     at emitOne (events.js:95:20)
20 verbose stack     at Request.emit (events.js:182:7)
20 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:963:12)
21 verbose statusCode 404
22 verbose pkgid ownCloud-news
23 verbose cwd /var/www/owncloud/apps/news
24 error Linux 3.16.0-4-amd64
25 error argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "ownCloud-news"
26 error node v5.10.1
27 error npm  v3.8.3
28 error code E404
29 error 404 Registry returned 404 for GET on https://registry.npmjs.org/ownCloud-news
30 error 404
31 error 404 'ownCloud-news' is not in the npm registry.
32 error 404 Your package name is not valid, because
33 error 404 1. name can no longer contain capital letters
34 error 404 Note that you can also install from a
35 error 404 tarball, folder, http url, or git url.
36 verbose exit [ 1, true ]
```

## Output from console executing make command
```
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! ownCloud-news@ prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ownCloud-news@ prebuild script 'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ownCloud-news package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ownCloud-news
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ownCloud-news
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/owncloud/apps/news/js/npm-debug.log
Makefile:86: recipe for target 'npm' failed
make[1]: *** [npm] Error 1
make[1]: Leaving directory '/var/www/owncloud/apps/news'
Makefile:61: recipe for target 'build' failed
make: *** [build] Error 2
root@nuc:/var/www/owncloud/apps/news# npm bugs ownCloud-news
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "ownCloud-news"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ownCloud-news
npm ERR! 404 
npm ERR! 404  'ownCloud-news' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Thanks for your help & let me know in case you need more info.

**Comment by BernhardPosselt** [comment]
make as root is not possible, can you attach the composer debug message?

**Comment by MrMontesa** [comment]
Thanks for your swift reply. Here's the message from composer

```
nuc:/owncloud/apps/news$ sudo -u www-data make
make composer
make[1]: Entering directory '/var/www/owncloud/apps/news'
No composer command available, downloading a copy from the web
mkdir -p /var/www/owncloud/apps/news/build/tools
curl -sS https://getcomposer.org/installer | php
All settings correct for using Composer
PHP Warning:  file_put_contents(/var/www/.composer/keys.dev.pub): failed to open stream: No such file or directory in - on line 407
PHP Warning:  file_put_contents(/var/www/.composer/keys.tags.pub): failed to open stream: No such file or directory in - on line 424
Downloading 1.0.0...
PHP Warning:  openssl_verify(): supplied key param cannot be coerced into a public key in - on line 514
PHP Warning:  openssl_free_key() expects parameter 1 to be resource, boolean given in - on line 515
Signature mismatch, could not verify the phar file integrity
Makefile:72: recipe for target 'composer' failed
make[1]: *** [composer] Error 1
make[1]: Leaving directory '/var/www/owncloud/apps/news'
Makefile:61: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by BernhardPosselt** [comment]
Looks to me like /var/www is not write/readable by www-data, can you check?

**Comment by MrMontesa** [comment]
/var/www is owned by root:root. Thats the default I guess. When manually changing to owner to www-data the  make process in fact continues and finishes properly, which is good.

Since /var/www is a root folder and Apache DocRoot's are folders below this one, www-data should not need to write there, or?

**Comment by BernhardPosselt** [comment]
I think composer tries to create some settings in the homefolder of the current user. So sudo -u www-data apparently has /var/ww as home folder. It tries to write to that folder and fails.

**Comment by MrMontesa** [comment]
Yes, /var/www is $HOME for www-data. Nice catch that the user cant write to its own home by default.
Thanks for your help, I think we can savely close this.

**Comment by BernhardPosselt** [comment]
http://unix.stackexchange.com/questions/91384/how-is-sudo-set-to-not-change-home-in-ubuntu-and-how-to-disable-this-behavior
