### ISSUE TITLE
Ubuntu 16.04 not stable yet

### ISSUE THREAD

**Issue by sedrubal** [owncloud/news#968]
## Explain the Problem
Upgrading to owncloud `9.0.1.3` breaks news app. I think this is because of upgrading news from `7....` to `8....` and news 8 needs `PHP 5.6` which is not available in Ubuntu `14.04 LTS`. In README you write that ubuntu 16.04 is required, but this is not even released yet! I think you should try to support and require stable products.

## Steps to Reproduce
Explain what you did to encounter the issue
1. Use ubuntu 14.04
2. Try to install oc and news app

## System Information
* News app version: 7.1.2 (not working...)
* ownCloud version: 9.0.1.3
* PHP version: 5.5.9
* Database and version: mariadb
* Browser and version: latest Firefox
* Distribution and version: Ubuntu 14.04 LTS

**Comment by BernhardPosselt** [comment]
Upgrading should not break the app. In fact it should not be possible to upgrade it if it's not compatible. Please open a bug in core.

Other than that simply use an older release from the releases page ;)

**Comment by BernhardPosselt** [comment]
Other than that you can always install a newer php version on 14.04 ;)

**Comment by sedrubal** [comment]
But it's never a good idea to add a external ppa to production systems...

**Comment by BernhardPosselt** [comment]
Then compile it from source. Or simply wait 11 days. Or use an older version ;)

**Comment by sedrubal** [comment]
mh ok... But is there currently the opportunity to run news on ubuntu 14.04 with php 5.5.9 and owncloud 9.0.1?

**Comment by BernhardPosselt** [comment]
Sure :)

Install the 7.1.2 version which is the last version that runs on 5.5: https://github.com/owncloud/news/releases/tag/7.1.2 see https://github.com/owncloud/news#installing-from-archive

**Comment by sedrubal** [comment]
Oh ok thanks ;)

But then I get "Internal Server Errors":

```json
{
  "app":"index",
  "message":"Exception: {
    \"Exception\":\"BadFunctionCallException\",\"Message\":\"basicAuthUser is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(145): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('basicAuthUser', Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setBasicAuthUse...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCA\\\\News\\\\Db\\\\Feed->setBasicAuthUser(NULL)\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(306): call_user_func('OCA\\\\News\\\\Db\\\\Fee...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(325): OCP\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/db\\\/feedmapper.php(69): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT `feeds`....', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/service\\\/feedservice.php(72): OCA\\\\News\\\\Db\\\\FeedMapper->findAllFromUser('sedrubal')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/controller\\\/feedcontroller.php(64): OCA\\\\News\\\\Service\\\\FeedService->findAll('sedrubal')\\n#9 [internal function]: OCA\\\\News\\\\Controller\\\\FeedController->index()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FeedController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(276): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(882): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/feed...')\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php\",\"Line\":114}","level":3,"method":"GET","url":"\/index.php\/apps\/news\/feeds"
}
```

and

```json
{
  "app":"index",
  "message":"Exception: {
    \"Exception\":\"BadFunctionCallException\",\"Message\":\"lastModified is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(145): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('lastModified', Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setLastModified', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCA\\\\News\\\\Db\\\\Folder->setLastModified('0')\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(306): call_user_func('OCA\\\\News\\\\Db\\\\Fol...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(325): OCP\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/db\\\/foldermapper.php(40): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT * FROM `...', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/service\\\/folderservice.php(48): OCA\\\\News\\\\Db\\\\FolderMapper->findAllFromUser('sedrubal')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/controller\\\/foldercontroller.php(55): OCA\\\\News\\\\Service\\\\FolderService->findAll('sedrubal')\\n#9 [internal function]: OCA\\\\News\\\\Controller\\\\FolderController->index()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FolderController), 'index')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FolderController), 'index')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FolderControlle...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(276): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(882): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/fold...')\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php\",\"Line\":114}","level":3,"method":"GET","url":"\/index.php\/apps\/news\/folders"
}
```

**Comment by BernhardPosselt** [comment]
See https://github.com/owncloud/news#i-am-getting-doctrine-dbal-exception-invalidfieldnameexception-column-not-found-1054-unknown-column-some_column-or-badfunctioncallexception-somecolumn-is-not-a-valid-attribute

**Comment by BernhardPosselt** [comment]
BTW in your case it looks like you did not replace all files. There are some old files hanging aground that cause this.

**Comment by sedrubal** [comment]
Ich checked out the git and it is clean, so there can't any other files. I think the problem is, that I had to downgrade from 8 to 7 and now it doesn't work again... So I have to wait until ubuntu 16.04 is released and I can use news 8...

**Comment by BernhardPosselt** [comment]
Downgrading does not work you need to migrate the database schema manually then. Should be in the readme

**Comment by BernhardPosselt** [comment]
@sedrubal I've added a more detailed explanation https://github.com/owncloud/news#i-am-getting-doctrine-dbal-exception-invalidfieldnameexception-column-not-found-1054-unknown-column-some_column-or-badfunctioncallexception-somecolumn-is-not-a-valid-attribute
